image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - davidanson.vscode-markdownlint@0.39.0:ixxSqTxD2d06+N5ugddwtg==
    - https://github.com/PowerShell/vscode-powershell/releases/download/v2021.2.2/PowerShell-2021.2.2.vsix
